#!/bin/sh
set -e

# RCCR Node Mapper - Interactive node role assignment
# Maps discovered hosts to control/target roles and generates inventory

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# ===================================================================
# Configuration
# ===================================================================

DISCOVERED_HOSTS="${1:-/tmp/rccr-discovered-hosts.txt}"
INVENTORY_FILE="$PROJECT_DIR/inventory.yml"

# ===================================================================
# Functions
# ===================================================================

log() {
    echo "[$(date +'%H:%M:%S')] $*"
}

# Interactive host mapping
map_nodes() {
    local hosts="$1"
    local control_nodes=""
    local target_nodes=""

    echo "╔═══════════════════════════════════════════════════════════════════╗"
    echo "║                    Interactive Node Mapping                       ║"
    echo "╚═══════════════════════════════════════════════════════════════════╝"
    echo ""
    echo "For each host, specify its role:"
    echo "  [c] Control Node (cluster manager)"
    echo "  [t] Target Node (worker)"
    echo "  [s] Skip (ignore this host)"
    echo ""

    i=1
    echo "$hosts" | while read -r host; do
        if [ -z "$host" ]; then
            continue
        fi

        echo "───────────────────────────────────────────────────────────────────"
        echo "Host #$i: $host"
        echo ""

        # Get hostname if possible
        HOSTNAME=$(timeout 2 ssh -o ConnectTimeout=1 -o StrictHostKeyChecking=no root@"$host" hostname 2>/dev/null || echo "unknown")
        if [ "$HOSTNAME" != "unknown" ]; then
            echo "  Detected hostname: $HOSTNAME"
        fi

        while true; do
            printf "  Role [c/t/s]: "
            read -r role

            case "$role" in
                c|C)
                    echo "  → Control Node"
                    echo "$host" >> /tmp/rccr-control-nodes.txt
                    break
                    ;;
                t|T)
                    echo "  → Target Node"
                    echo "$host" >> /tmp/rccr-target-nodes.txt
                    break
                    ;;
                s|S)
                    echo "  → Skipped"
                    break
                    ;;
                *)
                    echo "  Invalid input. Please enter c, t, or s."
                    ;;
            esac
        done

        echo ""
        i=$((i + 1))
    done
}

# Generate Ansible inventory
generate_inventory() {
    local control_file="/tmp/rccr-control-nodes.txt"
    local target_file="/tmp/rccr-target-nodes.txt"

    echo ""
    log "Generating Ansible inventory..."

    # Start inventory
    cat > "$INVENTORY_FILE" <<'EOF'
# RCCR Cluster Inventory
# Generated by node_mapper.sh

all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

EOF

    # Add control nodes
    if [ -f "$control_file" ] && [ -s "$control_file" ]; then
        cat >> "$INVENTORY_FILE" <<EOF
control:
  hosts:
EOF
        i=1
        while read -r host; do
            [ -z "$host" ] && continue
            cat >> "$INVENTORY_FILE" <<EOF
    control-node-$i:
      ansible_host: $host
EOF
            i=$((i + 1))
        done < "$control_file"
        echo "" >> "$INVENTORY_FILE"
    fi

    # Add target nodes
    if [ -f "$target_file" ] && [ -s "$target_file" ]; then
        cat >> "$INVENTORY_FILE" <<EOF
targets:
  hosts:
EOF
        i=1
        while read -r host; do
            [ -z "$host" ] && continue
            cat >> "$INVENTORY_FILE" <<EOF
    target-node-$i:
      ansible_host: $host
EOF
            i=$((i + 1))
        done < "$target_file"
        echo "" >> "$INVENTORY_FILE"
    fi

    # Cleanup temp files
    rm -f "$control_file" "$target_file"

    log "Inventory generated: $INVENTORY_FILE"
}

# Display summary
display_summary() {
    echo ""
    echo "╔═══════════════════════════════════════════════════════════════════╗"
    echo "║                       Mapping Complete                            ║"
    echo "╚═══════════════════════════════════════════════════════════════════╝"
    echo ""

    if [ -f "$INVENTORY_FILE" ]; then
        echo "Inventory file:"
        echo "───────────────────────────────────────────────────────────────────"
        cat "$INVENTORY_FILE"
        echo "───────────────────────────────────────────────────────────────────"
    fi

    echo ""
    echo "Next steps:"
    echo "  1. Review inventory: cat $INVENTORY_FILE"
    echo "  2. Install Python on targets: ansible-playbook playbooks/install-python.yml"
    echo "  3. Run setup: ansible-playbook playbooks/setup.yml"
    echo ""
}

# ===================================================================
# Main
# ===================================================================

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                      RCCR Node Mapper                              ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""

# Check if discovered hosts file exists
if [ ! -f "$DISCOVERED_HOSTS" ]; then
    log "ERROR: Discovered hosts file not found: $DISCOVERED_HOSTS"
    log "Please run network_scan.sh first"
    exit 1
fi

HOSTS=$(cat "$DISCOVERED_HOSTS")
if [ -z "$HOSTS" ]; then
    log "ERROR: No hosts found in $DISCOVERED_HOSTS"
    exit 1
fi

HOST_COUNT=$(echo "$HOSTS" | grep -c '.' || echo 0)
log "Found $HOST_COUNT host(s) to map"
echo ""

# Clear temp files
rm -f /tmp/rccr-control-nodes.txt /tmp/rccr-target-nodes.txt

# Interactive mapping
map_nodes "$HOSTS"

# Generate inventory
generate_inventory

# Display summary
display_summary
